// <auto-generated />
namespace TNAI.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PostComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostComment));
        
        string IMigrationMetadata.Id
        {
            get { return "202205291845035_PostComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
